[package]
name = "taws_primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uom = "0.31"
ordered-float = { version = "2.0", default-features = false }
